name: Run units tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install cffi and virtualenv
        run: pip install cffi virtualenv
      - name: Install RUST toolchain
        uses: actions-rs/toolchain@v1
        id: rustup
        with:
          profile: minimal
          toolchain: nightyly
          override: true
      - name: Build bindings
        run: |
          pip install maturin
          maturin develop
      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests.py
